# This is a simple norminette validation action.
name: 42-C-Norminette

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: ''
